services:
  - type: web
    name: ai-call-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
    domains:
      - ai-call-backend-waxe.onrender.com
